# Configuración para Railway y local
spring.datasource.url=jdbc:postgresql://${PGHOST:metro.proxy.rlwy.net}:${PGPORT:50603}/${PGDATABASE:railway}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:JxNfSDQNNOaDvYUSUxRzrqmnNDOicIoZ}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Server
server.port=${PORT:8083}

# Google Sheets
google.spreadsheet.id=${GOOGLE_SPREADSHEET_ID:13fWsFYrAuHF3-_s5mQoyX1qm8rVGdzMRyqmz4zp39wM}

# Configurar zona horaria para Hibernate/JPA
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima

# Configurar zona horaria para Jackson (JSON)
spring.jackson.time-zone=America/Lima

